name: Release

on:
    push:
        branches:
            - main
        paths:
            - 'packages/**'
            - '.changeset/**'
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
            pull-requests: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: pnpm/action-setup@v2
              with:
                  version: 8

            - uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  registry-url: 'https://registry.npmjs.org/'
                  cache: 'pnpm'
                  always-auth: true

            - name: Install dependencies
              run: pnpm install

            - name: Build all packages
              run: pnpm run packages:build

            - name: Create version PR or publish
              id: changesets
              uses: changesets/action@v1
              with:
                  version: pnpm changeset version
                  publish: pnpm release
                  commit: 'ci(changeset): version packages'
                  title: 'ci(changeset): version packages'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
